version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb+srv://ezeikel:Password123@crownd-dev-oxmrv.mongodb.net/admin?retryWrites=true&w=majority
            database: prisma