name: Deploy to Digital Ocean Droplet CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy via ssh
        uses: fifsky/ssh-action@v0.0.4
        with:
          command: |
            sh deploy.sh
          host: ${{ secrets.HOST }}
          user: ezeikel
          pass: ${{ secrets.PASSWORD }}
